const fs = require("fs");
const { parse } = require("csv-parse/sync");

function flattenSlug(slug) {
  return String(slug || "").replace(/\//g, "-");
}

function loadCsvCollection(filePath, { slugField = "Slug" } = {}) {
  const raw = fs.readFileSync(filePath, "utf8");
  const rows = parse(raw, {
    columns: true,
    skip_empty_lines: true,
    trim: true,
    relax_column_count: true,
  });

  const flattened = [];
  const items = rows.map((row) => {
    const originalSlug = row[slugField];
    const slug = flattenSlug(originalSlug);
    if (slug !== originalSlug) {
      flattened.push({ original: originalSlug, flattened: slug });
    }
    return {
      ...row,
      slug,
      originalSlug,
      body: "",
    };
  });

  return { items, flattened };
}

function writeFlattenReport(entries, outPath) {
  const lines = [
    "Slug flatten report — confirm with Jaxon (SEO URL plan change)",
    "Generated by scripts/load-csv.js",
    "",
    ...entries.map((e) => `${e.original} -> ${e.flattened}`),
    "",
  ];
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
}

module.exports = { flattenSlug, loadCsvCollection, writeFlattenReport };
