module.exports = {
  en: {
    skip: "Skip to content",
    home: "Home",
    check: "Check eligibility",
    programs: "Programs",
    pricing: "Pricing",
    affiliate: "Become an Affiliate",
    about: "About",
    standards: "Our standards",
    faq: "Questions",
    contact: "Contact",
    callUsNow: "Call us now: ",
    langSwitchLabel: "Español",
    footerTagline: "Guiding families through federal RECA compensation claims.",
    footerLegal:
      "Downwinders Advocates assists claimants and surviving families in filing claims under the Radiation Exposure Compensation Act (RECA). Eligibility and final compensation determinations are made by the U.S. Department of Justice under federal statutory guidelines.",
    footerStandards: "Our standards & commitments",
    ctaCheck: "Check Eligibility Now!",
    ctaDiscovery: "Book A 30-Minute Consultation",
    brandSubtitle: "RECA Claim Specialists",
  },
  es: {
    skip: "Saltar al contenido",
    home: "Inicio",
    check: "Verificar elegibilidad",
    programs: "Programas",
    pricing: "Precios",
    affiliate: "Hazte afiliado",
    about: "Nosotros",
    standards: "Nuestros estándares",
    faq: "Preguntas",
    contact: "Contacto",
    callUsNow: "Llámenos ahora: ",
    langSwitchLabel: "English",
    footerTagline: "Guiando a las familias a través de los reclamos de compensación federal RECA.",
    footerLegal:
      "Downwinders Advocates ayuda a los solicitantes y familiares sobrevivientes a presentar reclamos bajo la Ley de Compensación por Exposición a la Radiación (RECA). Las determinaciones de elegibilidad y compensación final las realiza el Departamento de Justicia de EE. UU.",
    footerStandards: "Nuestros estándares",
    ctaCheck: "Verificar elegibilidad",
    ctaDiscovery: "Reservar consulta de 30 minutos",
    draftBanner:
      "Borrador de traducción automática para revisión — no es texto aprobado por el abogado. Para ayuda en español con reclamos RECA, llámenos al (801) 704-5629.",
    brandSubtitle: "Especialistas en reclamos RECA",
  },
};
